# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  datingapp:
    image: datingapp
    build:
      context: .
      dockerfile: DatingApp.API/Dockerfile
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
   ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu 
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "pass3321PASS"
      MSSQL_PID: Express
    ports: 
      - 1433:1433
